ALTER TABLE collections
  ADD COLUMN IF NOT EXISTS auto_type TEXT,
  ADD COLUMN IF NOT EXISTS auto_tag TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS auto_favorite BOOLEAN,
  ADD COLUMN IF NOT EXISTS auto_min_rating INTEGER;
