package config

import (
	"errors"
	"os"
	"path/filepath"
	"testing"
)

func TestValidateRejectsMissingSecret(t *testing.T) {
	t.Parallel()

	cfg := &Config{
		DatabaseURL: "postgres://example",
		SecretKey:   "",
		JWTSecret:   "",
	}

	if err := cfg.validate(); err == nil {
		t.Fatal("expected missing secrets to be rejected")
	}
}

func TestValidateRejectsPlaceholderSecret(t *testing.T) {
	t.Parallel()

	cfg := &Config{
		DatabaseURL: "postgres://example",
		SecretKey:   "change-me-in-production-use-a-long-random-string",
		JWTSecret:   "this-is-a-valid-jwt-secret-value-12345",
	}

	if err := cfg.validate(); err == nil {
		t.Fatal("expected placeholder secret to be rejected")
	}
}

func TestValidateAcceptsLongRandomSecrets(t *testing.T) {
	t.Parallel()

	cfg := &Config{
		DatabaseURL: "postgres://example",
		SecretKey:   "this-is-a-valid-secret-key-value-12345",
		JWTSecret:   "this-is-a-valid-jwt-secret-value-12345",
	}

	if err := cfg.validate(); err != nil {
		t.Fatalf("expected secrets to be accepted, got %v", err)
	}
}

func TestLoadGeneratesPersistentSecretWhenMissing(t *testing.T) {
	secretFile := filepath.Join(t.TempDir(), "secret.key")

	t.Setenv("DATABASE_URL", "postgres://example")
	t.Setenv("SECRET_KEY", "")
	t.Setenv("SECRET_KEY_FILE", secretFile)
	t.Setenv("JWT_SECRET", "")

	cfg, err := Load()
	if err != nil {
		t.Fatalf("expected config to load, got %v", err)
	}

	if !cfg.SecretKeyAutoGenerated {
		t.Fatal("expected secret key to be auto-generated on first load")
	}
	if cfg.SecretKey == "" {
		t.Fatal("expected generated secret key to be non-empty")
	}
	if cfg.JWTSecret != cfg.SecretKey {
		t.Fatal("expected JWT secret to fall back to generated secret key")
	}

	raw, err := os.ReadFile(secretFile)
	if err != nil {
		t.Fatalf("expected secret file to be written, got %v", err)
	}
	if got := string(raw); got == "" {
		t.Fatal("expected secret file contents to be non-empty")
	}

	cfgAgain, err := Load()
	if err != nil {
		t.Fatalf("expected config to reload, got %v", err)
	}

	if cfgAgain.SecretKey != cfg.SecretKey {
		t.Fatal("expected persisted secret key to be reused on subsequent loads")
	}
	if cfgAgain.SecretKeyAutoGenerated {
		t.Fatal("expected second load to reuse existing secret key file")
	}
}

func TestLoadUsesExplicitSecretWithoutWritingFile(t *testing.T) {
	secretFile := filepath.Join(t.TempDir(), "secret.key")
	explicitSecret := "this-is-a-valid-secret-key-value-12345"

	t.Setenv("DATABASE_URL", "postgres://example")
	t.Setenv("SECRET_KEY", explicitSecret)
	t.Setenv("SECRET_KEY_FILE", secretFile)
	t.Setenv("JWT_SECRET", "")

	cfg, err := Load()
	if err != nil {
		t.Fatalf("expected config to load, got %v", err)
	}

	if cfg.SecretKey != explicitSecret {
		t.Fatalf("expected explicit secret key to be used, got %q", cfg.SecretKey)
	}
	if cfg.SecretKeyAutoGenerated {
		t.Fatal("expected explicit secret key not to be marked as auto-generated")
	}
	if cfg.JWTSecret != explicitSecret {
		t.Fatal("expected JWT secret to fall back to explicit secret key")
	}

	_, err = os.Stat(secretFile)
	if !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("expected no secret key file to be written, got %v", err)
	}
}
