// Package config loads application configuration from environment variables.
package config

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// Config holds all runtime configuration for Tanuki.
type Config struct {
	// Database
	DatabaseURL string

	// Cache / queue
	RedisURL string

	// Filesystem paths
	MediaPath      string
	ThumbnailsPath string
	DownloadsPath  string
	InboxPath      string

	// Security
	SecretKey              string
	SecretKeyFile          string
	SecretKeyAutoGenerated bool

	// HTTP server
	Port string

	// Logging
	LogLevel string

	// Scanner
	ScanInterval int // seconds

	// Download manager
	MaxConcurrentDownloads int
	RateLimitDelay         int // milliseconds
	DownloaderCookiesFile  string
	YtDlpImpersonate       string
	HDoujinModulesPath     string
	HDoujinModulesEnabled  bool

	// Auto-tagging (v0.4)
	SauceNAOAPIKey             string
	IQDBEnabled                bool
	AutoTagSimilarityThreshold int // percentage 0-100
	AutoTagOnScan              bool
	AutoTagRateLimitMs         int // milliseconds between API requests

	// Duplicate detection (v0.5)
	DuplicateThreshold int  // max Hamming distance to consider duplicate
	PHashOnScan        bool // compute pHash during scan

	// Authentication (v0.6)
	JWTSecret           string
	JWTExpiryHours      int
	RegistrationEnabled bool

	// Plugins (v1.0)
	PluginsPath    string
	PluginsEnabled bool
}

// Load reads configuration from environment variables, applying defaults where
// values are absent.
func Load() (*Config, error) {
	secretKeyFile := strings.TrimSpace(getEnv("SECRET_KEY_FILE", "/app/config/secret.key"))
	secretKey, autoGenerated, err := resolveSecretKey(
		strings.TrimSpace(getEnv("SECRET_KEY", "")),
		secretKeyFile,
	)
	if err != nil {
		return nil, err
	}

	jwtSecret, err := resolveJWTSecret(strings.TrimSpace(getEnv("JWT_SECRET", "")), secretKey)
	if err != nil {
		return nil, err
	}

	cfg := &Config{
		DatabaseURL:            getEnv("DATABASE_URL", "postgresql://tanuki:secret@localhost:5432/tanuki"),
		RedisURL:               getEnv("REDIS_URL", "redis://localhost:6379"),
		MediaPath:              getEnv("MEDIA_PATH", "/media"),
		ThumbnailsPath:         getEnv("THUMBNAILS_PATH", "/thumbnails"),
		DownloadsPath:          getEnv("DOWNLOADS_PATH", "/media"),
		InboxPath:              getEnv("INBOX_PATH", "/inbox"),
		SecretKey:              secretKey,
		SecretKeyFile:          secretKeyFile,
		SecretKeyAutoGenerated: autoGenerated,
		Port:                   getEnv("PORT", "8080"),
		LogLevel:               getEnv("LOG_LEVEL", "info"),
		ScanInterval:           getEnvInt("SCAN_INTERVAL", 300),
		MaxConcurrentDownloads: getEnvInt("MAX_CONCURRENT_DOWNLOADS", 3),
		RateLimitDelay:         getEnvInt("RATE_LIMIT_DELAY", 1000),
		DownloaderCookiesFile:  getEnv("DOWNLOADER_COOKIES_FILE", ""),
		YtDlpImpersonate:       getEnv("YTDLP_IMPERSONATE", "chrome"),
		HDoujinModulesPath:     getEnv("HDOUJIN_MODULES_PATH", "/app/hdoujin/modules/lua"),
		HDoujinModulesEnabled:  getEnvBool("HDOUJIN_MODULES_ENABLED", true),

		// Auto-tagging (v0.4)
		SauceNAOAPIKey:             getEnv("SAUCENAO_API_KEY", ""),
		IQDBEnabled:                getEnvBool("IQDB_ENABLED", true),
		AutoTagSimilarityThreshold: getEnvInt("AUTOTAG_SIMILARITY_THRESHOLD", 80),
		AutoTagOnScan:              getEnvBool("AUTOTAG_ON_SCAN", false),
		AutoTagRateLimitMs:         getEnvInt("AUTOTAG_RATE_LIMIT_MS", 5000),

		// Duplicate detection (v0.5)
		DuplicateThreshold: getEnvInt("DUPLICATE_THRESHOLD", 10),
		PHashOnScan:        getEnvBool("PHASH_ON_SCAN", true),

		// Authentication (v0.6)
		JWTSecret:           jwtSecret,
		JWTExpiryHours:      getEnvInt("JWT_EXPIRY_HOURS", 24),
		RegistrationEnabled: getEnvBool("REGISTRATION_ENABLED", true),

		// Plugins (v1.0)
		PluginsPath:    getEnv("PLUGINS_PATH", "/app/config/plugins"),
		PluginsEnabled: getEnvBool("PLUGINS_ENABLED", true),
	}

	if err := cfg.validate(); err != nil {
		return nil, err
	}

	return cfg, nil
}

func (c *Config) validate() error {
	if c.DatabaseURL == "" {
		return fmt.Errorf("DATABASE_URL is required")
	}
	if err := validateSecretValue("SECRET_KEY", c.SecretKey); err != nil {
		return err
	}
	if err := validateSecretValue("JWT_SECRET", c.JWTSecret); err != nil {
		return err
	}
	return nil
}

// ServerAddr returns the TCP address string for net/http.
func (c *Config) ServerAddr() string {
	return ":" + c.Port
}

// ─── helpers ─────────────────────────────────────────────────────────────────

func getEnv(key, fallback string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	return fallback
}

func getEnvInt(key string, fallback int) int {
	v := os.Getenv(key)
	if v == "" {
		return fallback
	}
	n, err := strconv.Atoi(v)
	if err != nil {
		return fallback
	}
	return n
}

func getEnvBool(key string, fallback bool) bool {
	v := os.Getenv(key)
	if v == "" {
		return fallback
	}
	b, err := strconv.ParseBool(v)
	if err != nil {
		return fallback
	}
	return b
}

func validateSecretValue(name, value string) error {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return fmt.Errorf("%s must be set", name)
	}
	if len(trimmed) < 32 {
		return fmt.Errorf("%s must be at least 32 characters", name)
	}
	if isPlaceholderSecret(trimmed) {
		return fmt.Errorf("%s must not use a checked-in placeholder value", name)
	}
	return nil
}

func resolveSecretKey(explicitSecret, secretFile string) (string, bool, error) {
	explicitSecret = strings.TrimSpace(explicitSecret)
	if explicitSecret != "" && !isPlaceholderSecret(explicitSecret) {
		return explicitSecret, false, nil
	}

	if strings.TrimSpace(secretFile) == "" {
		return "", false, fmt.Errorf("SECRET_KEY_FILE must be set when SECRET_KEY is empty")
	}

	secret, autoGenerated, err := loadOrCreateSecretFile(secretFile)
	if err != nil {
		return "", false, err
	}
	return secret, autoGenerated, nil
}

func resolveJWTSecret(explicitSecret, fallbackSecret string) (string, error) {
	explicitSecret = strings.TrimSpace(explicitSecret)
	if explicitSecret == "" || isPlaceholderSecret(explicitSecret) {
		return fallbackSecret, nil
	}
	return explicitSecret, nil
}

func loadOrCreateSecretFile(path string) (string, bool, error) {
	path = filepath.Clean(strings.TrimSpace(path))
	if path == "" {
		return "", false, fmt.Errorf("secret key file path is empty")
	}

	if secret, err := readSecretFile(path); err == nil {
		return secret, false, nil
	} else if !errors.Is(err, fs.ErrNotExist) {
		if secret, waitErr := waitForValidSecretFile(path, 500*time.Millisecond); waitErr == nil {
			return secret, false, nil
		}
		return "", false, err
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return "", false, fmt.Errorf("create secret key directory: %w", err)
	}

	generatedSecret, err := generateSecretValue()
	if err != nil {
		return "", false, err
	}

	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err == nil {
		if _, writeErr := file.WriteString(generatedSecret + "\n"); writeErr != nil {
			_ = file.Close()
			_ = os.Remove(path)
			return "", false, fmt.Errorf("write secret key file: %w", writeErr)
		}
		if syncErr := file.Sync(); syncErr != nil {
			_ = file.Close()
			_ = os.Remove(path)
			return "", false, fmt.Errorf("sync secret key file: %w", syncErr)
		}
		if closeErr := file.Close(); closeErr != nil {
			_ = os.Remove(path)
			return "", false, fmt.Errorf("close secret key file: %w", closeErr)
		}
		return generatedSecret, true, nil
	}
	if !errors.Is(err, fs.ErrExist) {
		return "", false, fmt.Errorf("create secret key file: %w", err)
	}

	secret, readErr := waitForValidSecretFile(path, time.Second)
	if readErr != nil {
		return "", false, readErr
	}
	return secret, false, nil
}

func waitForValidSecretFile(path string, timeout time.Duration) (string, error) {
	deadline := time.Now().Add(timeout)
	var lastErr error

	for {
		secret, err := readSecretFile(path)
		if err == nil {
			return secret, nil
		}

		lastErr = err
		if time.Now().After(deadline) {
			return "", lastErr
		}

		time.Sleep(25 * time.Millisecond)
	}
}

func readSecretFile(path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}

	secret := strings.TrimSpace(string(raw))
	if err := validateSecretValue("SECRET_KEY_FILE", secret); err != nil {
		return "", err
	}
	return secret, nil
}

func generateSecretValue() (string, error) {
	buf := make([]byte, 48)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate secret key: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

func isPlaceholderSecret(value string) bool {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "",
		"change-me",
		"changeme",
		"change-me-in-production",
		"change-me-in-production-use-a-long-random-string",
		"replace-me",
		"secret":
		return true
	default:
		return false
	}
}
